[project]
name = "py-er-api"
version = "0.1.0"
description = "eternal return API(https://developer.eternalreturn.io/) python wrapper"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
